### ISSUE TITLE
Aggregating view events in ALSAlgorithm.scala rather than DataSource.scala

### ISSUE THREAD

**Issue by alex9311** [PredictionIO/template-scala-parallel-similarproduct#9]
I'm new to predictionio and DASE, been going through these older templates to understand how it all works. 

This template uses ALS.trainImplicit with view events which have been [aggregated](https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/develop/src/main/scala/ALSAlgorithm.scala#L88) in the **_train_** method of _**ALSAlgorithm.scala**_. 

The [basic recommender](https://templates.prediction.io/PredictionIO/template-scala-parallel-recommendation) has a guide to [switch to implicit feedback](https://docs.prediction.io/templates/recommendation/training-with-implicit-preference/). In this guide, the code to aggregate views in put in the _**readTraining**_ method of **_DataSource.scala_**.

Is there any difference between aggregating the view events in ALSAlgorithm.train versus DataSource.readTraining? 

Should the aggregating code on this template be moved to the readTraining method?

**Comment by k4hoo** [comment]
Effectively there is no difference. it depends on how you wanna partition the logic and structure code based on your needs

In the basic recommender example, since originally it's designed for "rating" prediction, we wanna show how you could read different type of event with least modification for demonstration purpose, and re-use the same [rating class](https://github.com/PredictionIO/template-scala-parallel-recommendation/blob/v0.3.2/src/main/scala/DataSource.scala#L98) as training data.

In this similar product template, we took one step further, which is to pass the actual [view event](https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/DataSource.scala#L106) as Training Data so that
1. it allows more flexibilities in the later stages regarding how to use these events. For example, different ways of aggregating/pre-processing events and
2. one can add additional event types in Training Data as well, rather than limited to just rating.

Sorry for confusion but hope it makes sense.

**Comment by alex9311** [comment]
Hi, thanks for the explanation, makes sense! 

Cheers
